// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMZmnJgSwN2oyon71_N6y4aX6pFas4GUI',
    appId: '1:98613072986:web:dc4e725465f42c1f483463',
    messagingSenderId: '98613072986',
    projectId: 'hanauta-bdc20',
    authDomain: 'hanauta-bdc20.firebaseapp.com',
    storageBucket: 'hanauta-bdc20.firebasestorage.app',
    measurementId: 'G-EB2B7Z23BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2xo7scCChTkvU0BagR1jf3Afpy6zRf8o',
    appId: '1:98613072986:android:9495469156657d9e483463',
    messagingSenderId: '98613072986',
    projectId: 'hanauta-bdc20',
    storageBucket: 'hanauta-bdc20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpq5KHYRDVYcDQs4epoTnj-nkP0DI6JFM',
    appId: '1:98613072986:ios:21632a54e5349aec483463',
    messagingSenderId: '98613072986',
    projectId: 'hanauta-bdc20',
    storageBucket: 'hanauta-bdc20.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.lyrics-anki-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpq5KHYRDVYcDQs4epoTnj-nkP0DI6JFM',
    appId: '1:98613072986:ios:d3692ce9cc6dc32e483463',
    messagingSenderId: '98613072986',
    projectId: 'hanauta-bdc20',
    storageBucket: 'hanauta-bdc20.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMZmnJgSwN2oyon71_N6y4aX6pFas4GUI',
    appId: '1:98613072986:web:df03b2e2ecd8a1fc483463',
    messagingSenderId: '98613072986',
    projectId: 'hanauta-bdc20',
    authDomain: 'hanauta-bdc20.firebaseapp.com',
    storageBucket: 'hanauta-bdc20.firebasestorage.app',
    measurementId: 'G-DCCMJ4GG4V',
  );
}
