// Mocks generated by Mockito 5.4.6 from annotations
// in lyrics_anki_app/test/features/lyrics/presentation/lyrics_notifier_saving_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:lyrics_anki_app/features/lyrics/data/lyrics_repository.dart'
    as _i3;
import 'package:lyrics_anki_app/features/lyrics/domain/entities/learning_mode.dart'
    as _i5;
import 'package:lyrics_anki_app/features/lyrics/domain/entities/lyrics.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAnalysisResult_0 extends _i1.SmartFake
    implements _i2.AnalysisResult {
  _FakeAnalysisResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LyricsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLyricsRepository extends _i1.Mock implements _i3.LyricsRepository {
  @override
  bool get isReady => (super.noSuchMethod(
        Invocation.getter(#isReady),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Stream<_i2.AnalysisResult> analyzeSong(
    String? title,
    String? artist,
    String? language, {
    _i5.LearningMode? learningMode = _i5.LearningMode.japanese,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeSong,
          [
            title,
            artist,
            language,
          ],
          {#learningMode: learningMode},
        ),
        returnValue: _i4.Stream<_i2.AnalysisResult>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.AnalysisResult>.empty(),
      ) as _i4.Stream<_i2.AnalysisResult>);

  @override
  _i4.Future<void> saveToHistory(_i2.HistoryItem? item) => (super.noSuchMethod(
        Invocation.method(
          #saveToHistory,
          [item],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveAnalysisResult(
    _i2.AnalysisResult? result,
    String? language, {
    _i5.LearningMode? learningMode = _i5.LearningMode.japanese,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAnalysisResult,
          [
            result,
            language,
          ],
          {#learningMode: learningMode},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i2.HistoryItem> getHistory({
    int? limit = 50,
    _i5.LearningMode? mode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [],
          {
            #limit: limit,
            #mode: mode,
          },
        ),
        returnValue: <_i2.HistoryItem>[],
        returnValueForMissingStub: <_i2.HistoryItem>[],
      ) as List<_i2.HistoryItem>);

  @override
  _i4.Stream<List<_i2.HistoryItem>> watchHistory({_i5.LearningMode? mode}) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchHistory,
          [],
          {#mode: mode},
        ),
        returnValue: _i4.Stream<List<_i2.HistoryItem>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i2.HistoryItem>>.empty(),
      ) as _i4.Stream<List<_i2.HistoryItem>>);

  @override
  _i4.Future<void> clearHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.AnalysisResult> parseAnalysisResult(
    String? jsonString, {
    bool? isReverseLearning = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseAnalysisResult,
          [jsonString],
          {#isReverseLearning: isReverseLearning},
        ),
        returnValue: _i4.Future<_i2.AnalysisResult>.value(_FakeAnalysisResult_0(
          this,
          Invocation.method(
            #parseAnalysisResult,
            [jsonString],
            {#isReverseLearning: isReverseLearning},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AnalysisResult>.value(_FakeAnalysisResult_0(
          this,
          Invocation.method(
            #parseAnalysisResult,
            [jsonString],
            {#isReverseLearning: isReverseLearning},
          ),
        )),
      ) as _i4.Future<_i2.AnalysisResult>);
}
